framework:
  - name: pytorch                                # possible values are tensorflow, mxnet and pytorch

calibration:
  - iterations: 10, 50

tuning:
  - metric:
      - topk: 1                                  # tuning metrics: accuracy 
    accuracy_criterion:
      - relative: 0.01                           # the tuning target of accuracy loss percentage: 1%
    timeout: 14400                                   # tuning timeout (seconds)
    random_seed: 9527                            # random seed
